---
- name: Converge
  hosts: instance
  become: true
  vars:
    local_role_name: "ansible-role-nexus"
    role_name: "{% if lookup('env','ROLE_NAME_FULL') %}{{ lookup('env','ROLE_NAME_FULL') }}{% else %}{{ local_role_name }}{% endif %}"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: get docker host ip
      become: yes
      shell: |
        set -o pipefail
        /sbin/ip route | awk '/default/ { print $3 }'
      args:
        executable: /bin/bash
      register: dockerhost_ip
      changed_when: false

  roles:
    - {
      role: "{{ role_name }}",
      service_nexus_host: "{{ dockerhost_ip.stdout }}",
      docker_volumes: [],
      debug_hide: false
    }
